### ISSUE TITLE
Ultralytics - Instance Segmentation : downsampling Issue

### ISSUE THREAD

**Issue by dustjr1565** [snuailab/waffle_hub#293]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar bug report.

### Bug

There is an issue with downsampling in ultralytics' instance segmentation.

GT (Ground Truth) Mask is disrupted, **and in severe cases, the GT disappears.**
Ultralytics performs downsampling. During this process, the GT mask can get disrupted or disappear
Reference: ultralytics/issues/6177

------------------------------------------------------------------------------------------------

ultralytics - instance segmentation에서 downsampling에 의한 문제가 있습니다.
- GT Mask 깨짐 현상이 발생하며, **심한경우 GT가 사라집니다**

ultralytics는 downsample을 수행합니다. 이 과정에서 GT 깨짐 및 심한경우 사라집니다.
reference: ultralytics/issues/6177

**Comment by dustjr1565** [comment]
use mask_ratio : 4 -> 1

**Comment by kimdanni** [comment]
You are correct in your understanding. Due to downsampling, it appears that loss is occurring, leading to aliasing in the mask. In severe cases, it seems that the Ground Truth (GT) disappears as a result of this loss. It is suggested that modifying the 'mask_ratio' in the advanced parameters may address this issue. 'mask_ratio' is utilized to determine the downsampling ratio during segmentation mask training. The default value for 'mask_ratio' is 4, meaning that the mask/image is downsampled by a factor of 4.

When 'mask_ratio' is set to 4, training speeds up significantly without substantial loss of accuracy, as mentioned in this [link](https://github.com/ultralytics/ultralytics/issues/1458). However, by setting 'mask_ratio' to 1 and keeping the image size the same as the original during training, it was observed that no loss occurred.
